import Head from "next/head";
import { GetServerSideProps } from "next";
import DataProvider from "../contexts/DataCategoryProvider";
import { resolveListRequests } from "../request/SmarthphonesRequest";
import { pokemonInfo } from "../types/types";
import CategoryContent from "../content/category";

type props = {
     data: pokemonInfo[];
};

const Smarthphone = ({ data }: props) => {
     
     return (
          <>
               <Head>
                    <title>Amerifan - smarthphones</title>
                    <meta name="description" content="Generated by create next app" />
               </Head>
               <main>
                    <DataProvider data={data}>
                         <CategoryContent name="smartphones" />
                    </DataProvider>
               </main>
          </>
     );
};

export default Smarthphone;

export const getServerSideProps: GetServerSideProps = async () => {
     const { data, error } = await resolveListRequests();

     if (error) {
          return { notFound: true };
     }
     return {
          props: {
               data: data,
          },
     };
};
