import Head from "next/head";
import { GetStaticProps } from "next";
import ProductsByCategory from "../components/categoryContent";
import DataProvider from "../contexts/DataCategoryProvider";
import { resolveListRequests } from "../request/SmarthphonesRequest";
import { pokemonInfo } from "../types/types";

type props = {
     data: pokemonInfo[];
};

const Smarthphone = ({ data }: props) => {
     console.log("smarthpone render");
     return (
          <>
               <Head>
                    <title>Amerifan - smarthphones</title>
                    <meta name="description" content="Generated by create next app" />
               </Head>
               <main>
                    <DataProvider data={data}>
                         <ProductsByCategory />
                    </DataProvider>
               </main>
          </>
     );
};

export default Smarthphone;

export const getStaticProps: GetStaticProps = async () => {
     const { data, error } = await resolveListRequests();

     if (error) {
          return { notFound: true };
     }
     return {
          props: {
               data: data,
          },
     };
};
